name: Build

on:
  push:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build (${{ matrix.preset }})
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        preset: ['debug-gcc', 'debug-clang', 'release-gcc', 'release-clang', 'asan', 'tsan', 'ubsan']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Extract Version
        run: |
          echo "build_name=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "build_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "build_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "build_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "build_dir=build/${{ matrix.preset }}" >> $GITHUB_ENV
          cmake --version
          ninja --version          

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} -v

      - name: Publish Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.preset }}-${{ env.build_sha }}
          path: |
            ${{ env.build_dir }}/server
            ${{ env.build_dir }}/client
            ${{ env.build_dir }}/dns_client
            ${{ env.build_dir }}/http_client

      - name: Run Unit Tests
        id: tests
        run: ctest --preset ${{ matrix.preset }} --output-junit ${{ github.workspace }}/${{ env.build_dir }}/report.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@v3
        if: steps.tests.outcome == 'success' || steps.tests.outcome == 'failure'
        with:
          name: Tests (${{ matrix.preset }})
          path: ${{ env.build_dir }}/report.xml
          reporter: java-junit
