name: Build

on:
  push:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0

      - name: Generate Debug Project
        run: cmake -S . -D CMAKE_BUILD_TYPE=Debug -B ./build/Debug

      - name: Build Debug Project
        run: cmake --build ./build/Debug

      - name: Generate Release Project
        run: cmake -S . -D CMAKE_BUILD_TYPE=Release -B ./build/Release

      - name: Build Release Project
        run: cmake --build ./build/Release

#      - name: Test Project
#        runs: ctest --test-dir build/Debug
